version: '3.6'
services:
  app: 
    build: .
    container_name: Herbify
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - EXTERNAL_PORT=5000
      - PGUSER=Hola
      - PGPASSWORD=developer
      - PGDATABASE=Herbify
      - PGHOST=db # NAME OF THE SERVICE
    volumes:
      - /home/hola/Documents/source-code/Herbify:/app
    depends_on:
      - db
  db: 
    image: postgres:15-alpine
    container_name: herbifyDB
    environment:  
      POSTGRES_USER: Hola
      POSTGRES_DB: Herbify
      POSTGRES_PASSWORD: developer
    ports:
      - "5432:5432"
    volumes:
      - herbifyDB:/var/lib/postgresql/data
volumes:
  herbifyDB: {}